name: 'Sass scanner'
description: 'Want less Sass? Track it.'
author: 'JamOS'
inputs:
  repo-token:
    description: 'Github auth token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
