name: Test
on:
  push:
    branches:
      - master
  create:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v1
      - name: Install dependencies
        run: npm ci
      - name: Build and Package
        run: npm run all
      - name: Scan for sass files
        id: scan-for-sass
        uses: ./
      - name: Print the number of sass files left
        run: echo ${{ steps.scan-for-sass.outputs.sass-file-count }}
