name: Test
on:
  push:
    branches:
      - master
  create:
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Get source
        uses: actions/checkout@v1
      - name: Build and Package
        run: npm run all
      - name: Create a release draft for a version tag
        id: create-release-draft
        uses: ./
      - name: Print the URL of the release draft
        run: echo ${{ steps.create-release-draft.outputs.release-url }}
